# Generated by Django 3.2.7 on 2021-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('father_Name', models.CharField(max_length=50)),
                ('mother_Name', models.CharField(max_length=50)),
                ('last_Education', models.CharField(max_length=50)),
            ],
        ),
    ]
